export default [
    'Respiración automática desactivad... Digo, ¿Se te perdió algo?',
    'Me gusta el pan. ¿Medas?',
    'A Avocado no le gusta esto, quizás deberías volver...',
    'A Kirzu no le gusta esto, quizás deberías volver...',
    'A Nejire no le gusta esto, quizás deberías volver...',
    'A Andremor no le gusta esto, quizás deberías volver...',
    'A Socram no le gusta esto, quizás deberías volver...',
    'No hay nada por aquí... ¿Qué tal si volvemos a un lugar seguro?',
    'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    '2 + 2 = 🦆',
    'Sorry pero se dice palta.',
    'Sorry pero se dice aguacate.',
    'Parece que esta ruta no existe.',
    'Hey, creo que no deberias estar aqui.',
    'No hay nada, nadie...Ah espera ¿Y tú qué haces aquí?',
    'Avocado creó estos mensajes mientras estaba en clases... Lo bueno es que Kirzu le ayudó',
    'Ehrm, Esto es incómodo...',
    'QDEP Groovy.',
    'QDEP Rythm.',
    '* Inserte frase para un error 404 aquí *',
    'Llegaste al lugar secreto +10 puntos de estilo',
  
    'Ḩ̬̘͔͙̰̮̆̽̋ͩ͡o̗̟͇̬͙̘̳ͫͨ͘l̳͇͚͕͎̘̫̝͛ͮ̋ͤ̿͌̚a̩̙̥̮̫̙̜̦ͬ͊̌ͬ̈́̒͐.',
];
